Proceso de lectura de archivos CSV

In [14]:
import pandas as pd
import requests
import numpy as np
from pipeline import run_orchestator

In [2]:
df=pd.read_csv("Titanic.csv")
print(f'total lineas importadas:  {len(df)}')

total lineas importadas:  1309

In [3]:
def leer_datos_csv():
        source="Titanic.csv"
        df=pd.read_csv(source)
        print(f'total lineas importadas:  {len(df)}')
        return df

In [4]:
leer_datos_csv()

total lineas importadas:  1309

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [5]:
subject='cooking'
url = f"https://openlibrary.org/subjects/{subject}.json?limit=50"
response = requests.get(url)
data = response.json()
df = pd.json_normalize(data['works'])
df = df[['title', 'key', 'first_publish_year']]
print(f"Batch pulled {len(df)} book records.")

Batch pulled 50 book records.

In [6]:
df.head(10)

,title,key,first_publish_year
0,Kokuritsu Kokkai Toshokan shozō Meijiki kankō ...,/works/OL33207850W,1991
1,Frugal housewife,/works/OL107969W,1829
2,Boston Cooking-School cook book,/works/OL1798750W,1896
3,Como agua para chocolate,/works/OL953162W,1989
4,The Virginia house-wife,/works/OL2653703W,1824
5,On Cooking,/works/OL1874827W,1994
6,Old Cookery Books and Ancient Cuisine,/works/OL1086812W,1886
7,Joy of Cooking,/works/OL267968W,1931
8,The Bartender's Guide,/works/OL7418388W,1862
9,国立 国会 図書館 所蔵 明治期 刋行 図書 マイクロ版 集成,/works/OL39080200W,1991

In [8]:
ad1 = run_orchestator()

--- Lectura de csv
total lineas importadas:  1309
--- Lectura de titulos libros
Batch pulled 10 book records.
--- Lectura del clima en tiempo real
  > instantanea 1...
  > instantanea 2...
  > instantanea 3...
  > instantanea 4...
  > instantanea 5...
--- Resumen de datos sin transformar

📍 FUENTE: Titanic
Rows: 1309 | Columns: ['Passengerid', 'Age', 'Fare', 'Sex', 'sibsp', 'zero', 'zero.1', 'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6', 'Parch', 'zero.7', 'zero.8', 'zero.9', 'zero.10', 'zero.11', 'zero.12', 'zero.13', 'zero.14', 'Pclass', 'zero.15', 'zero.16', 'Embarked', 'zero.17', 'zero.18', '2urvived']
   Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0            1  22.0   7.2500    0      1     0       0       0       0
1            2  38.0  71.2833    1      1     0       0       0       0

   zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  Embarked  \
0       0  ...        0        0        0       3        0        0       2.0
1       0  ...        0        0        0       1        0        0       0.0

   zero.17  zero.18  2urvived
0        0        0         0
1        0        0         1

[2 rows x 28 columns]

📍 FUENTE: Libros
Rows: 10 | Columns: ['title', 'key', 'first_publish_year']
                  title                 key  first_publish_year
0  Nineteen Eighty-Four   /works/OL1168083W                1949
1                  Wool  /works/OL16800608W                2011

📍 FUENTE: clima
Rows: 5 | Columns: ['time', 'interval', 'temperature', 'windspeed', 'winddirection', 'is_day', 'weathercode']
               time  interval  temperature  windspeed  winddirection  is_day  \
0  2026-04-29T21:45       900         21.5        3.3            257       1
1  2026-04-29T21:45       900         21.5        3.3            257       1

   weathercode
0            0
1            0

--- Ejecutando transformaciones
  > Resumen de sobrevivientes Titanic...
  > Creando UniqueKey en Libros...
  > Promedio de temperatura en Clima...
  > Eliminando pasajeros menores de 10 años...

--- Resumen final de almacen_datos

📍 ENTRADA: Titanic
Rows: 1227 | Columns: ['Passengerid', 'Age', 'Fare', 'Sex', 'sibsp', 'zero', 'zero.1', 'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6', 'Parch', 'zero.7', 'zero.8', 'zero.9', 'zero.10', 'zero.11', 'zero.12', 'zero.13', 'zero.14', 'Pclass', 'zero.15', 'zero.16', 'Embarked', 'zero.17', 'zero.18', '2urvived']
   Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0            1  22.0   7.2500    0      1     0       0       0       0
1            2  38.0  71.2833    1      1     0       0       0       0

   zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  Embarked  \
0       0  ...        0        0        0       3        0        0       2.0
1       0  ...        0        0        0       1        0        0       0.0

   zero.17  zero.18  2urvived
0        0        0         0
1        0        0         1

[2 rows x 28 columns]

📍 ENTRADA: Libros
Rows: 10 | Columns: ['title', 'key', 'first_publish_year', 'UniqueKey']
                  title                 key  first_publish_year    UniqueKey
0  Nineteen Eighty-Four   /works/OL1168083W                1949   OL1168083W
1                  Wool  /works/OL16800608W                2011  OL16800608W

📍 ENTRADA: clima
Rows: 5 | Columns: ['time', 'interval', 'temperature', 'windspeed', 'winddirection', 'is_day', 'weathercode']
               time  interval  temperature  windspeed  winddirection  is_day  \
0  2026-04-29T21:45       900         21.5        3.3            257       1
1  2026-04-29T21:45       900         21.5        3.3            257       1

   weathercode
0            0
1            0

📍 ENTRADA: Titanic_Resumen
Rows: 2 | Columns: ['2urvived', 'Conteo']
        2urvived  Conteo
0  No sobrevivió     967
1     Sobrevivió     342

📍 ENTRADA: Clima_Resumen
Rows: 6 | Columns: ['Columna', 'Promedio']
       Columna  Promedio
0     interval     900.0
1  temperature      21.5

In [7]:
df=ad1['Titanic']

In [9]:
print(df.groupby("2urvived").size())

2urvived
0    967
1    342
dtype: int64

In [11]:
df_batch=ad1['Libros']
df_batch['UniqueKey']=df_batch["key"].str.split('/').str[-1]

In [12]:
ad1['Libros']=df_batch

In [16]:
df=ad1['Titanic']
#calculo de la media de valores que no son 0
media_fare=df.loc[df['Fare'] != 0, 'Fare'].mean()
#reemplaza los valores 0 con la media calculada
df['Fare']=df['Fare'].replace(0,media_fare)
df

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1222,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1223,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1224,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1225,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1226,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [18]:
df['Fare']=df['Fare'].replace(34.01778206611571,0)

In [17]:
print(media_fare)

34.01778206611571